### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by asari-mtr** [asari-mtr/link2md#1]
must
---
- [x] run from the context menu
- [x] run from the browser action
- [x] setting shortcut
- [x] remove icon from menubar (if do not remove, set a cool icon)
- [ ] When nothing is selected, the URL of the current page is copied
- [x] ~ignore internal links~
  - [x] also get internal links
- [x] ignore javascript
- [x] error handling
  - [x] when nothing select
- [ ] package and release
  - [Publish in the Chrome Web Store \- Google Chrome](https://developer.chrome.com/webstore/publish)
- [x] relative url to absolute url

want to
---
- [ ] make test code
- [ ] message on success
